FirebaseError: Missing or insufficient permissions. eror ini muncul tapi aku udah berhasil add kasir setelah add kasir tombol add kasir pun masoh bisa dijalani